Repository Dream-Catch/Balance-Catch-iOS, pull requests merged in 2023-06, with the labels that each got.

#41 [#38]Feat: 질문 리스트 응답받는 네트워크 통신 구현
  Balance-Catch-iOS/Balance-Catch-iOS.xcodeproj/project.pbxproj
  Balance-Catch-iOS/Balance-Catch-iOS/Balance_Catch_iOSApp.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Custom/WheelStylePicker/QuestionItemView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Custom/WheelStylePicker/QuestionPickerView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Extension/CancelBag.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Model/PlayerModel.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Model/Question.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Model/Response/QuestionDataModel.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Model/Response/ServerModel.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Model/UserQuestion.swift
  Balance-Catch-iOS/Balance-Catch-iOS/NetworkManager/NetworkManager.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Route/Route.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Strings/QuestionTexts.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/FirstTeamSpeakingView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/LaunchScreenView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/SecondTeamSpeakingView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/SelectQuestionView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/SelectTypeView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/TimerView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/UserFinalSelectView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/UserFirstSelectView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/ViewModel/QuestionDataViewModel.swift
Labels: 🐯 Feature

#62 [#61]Enhancement: 질문 좋아요 화면 스킵 버튼 구현
  Balance-Catch-iOS/Balance-Catch-iOS/Balance_Catch_iOSApp.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Custom/RoundedBlueButton.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/RecommandOrNotView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/WhoIsLoserView.swift
Labels: 🐼 enhancement

#63 Feature/check who is loser
  Balance-Catch-iOS/Balance-Catch-iOS.xcodeproj/project.pbxproj
  Balance-Catch-iOS/Balance-Catch-iOS/Custom/GameResultView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Custom/LoserButtonStyle.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Custom/PreferenceKey/ViewHeightKey.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Custom/PublicPickScoreView/ScoreView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Custom/RoundedBlueButton.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Extension/CGFloat+.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Extension/String+.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Model/PlayerModel.swift
  Balance-Catch-iOS/Balance-Catch-iOS/Route/Route.swift
  Balance-Catch-iOS/Balance-Catch-iOS/SupportingFiles/Assets.xcassets/Images/Bomb.imageset/Bomb.svg
  Balance-Catch-iOS/Balance-Catch-iOS/SupportingFiles/Assets.xcassets/Images/Bomb.imageset/Contents.json
  Balance-Catch-iOS/Balance-Catch-iOS/SupportingFiles/Assets.xcassets/Images/FourLeafClover.imageset/Contents.json
  Balance-Catch-iOS/Balance-Catch-iOS/SupportingFiles/Assets.xcassets/Images/FourLeafClover.imageset/FourLeafClover.svg
  Balance-Catch-iOS/Balance-Catch-iOS/SupportingFiles/Info.plist
  Balance-Catch-iOS/Balance-Catch-iOS/View/LaunchScreenView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/PlayerNameInputView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/PublicPickView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/RecommandOrNotView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/UserFinalSelectView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/UserFirstSelectView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/WhoIsLoserView.swift
Labels: 🐯 Feature

#65 [#64]Enhance: 광고가 안 나왔을 때도 대중 픽 뷰에서 애니메이션 적용
  Balance-Catch-iOS/Balance-Catch-iOS/Custom/PublicPickScoreView/ScoreView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/PlayerNumberInputView.swift
  Balance-Catch-iOS/Balance-Catch-iOS/View/PublicPickView.swift
Labels: 🐼 Enhancement
